# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Inform your name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Inform your last name', max_length=50, verbose_name='Surname'),
        ),
    ]
